inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Layout/FirstParameterIndentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - 'Rakefile'
Style/IfUnlessModifier:
  Enabled: false
Style/Next:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%i': '[]'
Style/RaiseArgs:
  EnforcedStyle: compact
Style/SignalException:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false
